name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          os: [windows-latest, macos-latest]
          # TODO: Add here also different build profiles (debug and release)
          # Consider how much running time it would take
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: setup rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        rustflags:
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gdk
      run:  | 
        sudo apt-get update && 
        sudo apt-get install libgtk-3-dev -y
    - name: setup rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        rustflags:
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
