name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_path: target/dist/enchanted-view
            asset_name: enchanted-view-linux
          - name: windows
            os: windows-latest
            artifact_path: target/dist/enchanted-view.exe
            asset_name: enchanted-view-windows.exe
          - name: macos
            os: macos-latest
            artifact_path: target/dist/enchanted-view
            asset_name: enchanted-view-macos
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags:
      - name: Build
        run: cargo build --profile dist --locked
      - name: Rename # Renaming to avoid duplicate file names when uploading to the release
        run: mv ${{ matrix.artifact_path }} ${{ matrix.asset_name }}
      - name: Display structure of downloaded files
        run: ls -R # For debugging
      - name: Upload bin to action artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}
  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Display structure of downloaded files
        run: ls -R # For debugging
        working-directory: bin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            bin/enchanted-view-linux/enchanted-view-linux
            bin/enchanted-view-macos/enchanted-view-macos
            bin/enchanted-view-windows.exe/enchanted-view-windows.exe

    
  